steps:
- bash: |
    set -e
    git clone -b azure-fix https://github.com/meain/cask "$HOME"/.cask
    echo "##vso[task.setvariable variable=PATH]$HOME/.cask/bin:$PATH"
  displayName: Install cask
  condition: and(succeeded(), ne(variables['Agent.OS'], 'Windows_NT'))

# TODO: Fix cask's issue with Python 3 on Windows. Basically, os.environb is not available.
# (os.supports_bytes_environ is False). The workaround is manually calling emacs with Powershell.
# For example:
#
#     emacs -Q --script' "$env:UserProfile\.cask\cask-cli.el -- package"
#
# See https://github.com/cask/cask/issues/285.
#
# TODO: Fix 'Select coding system' issue on Windows.
# See https://github.com/cask/cask/issues/341.
- powershell: |
    git clone -b azure-fix https://github.com/meain/cask "$env:UserProfile\.cask"
    echo "##vso[task.prependpath]$env:UserProfile\.cask\bin"
  displayName: Install cask (Windows)
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
